name: Github Actions Demo
run-name: ${{ github.actor }} is testing out github actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job is successfully triggerd by a ${{ github.event_name }} event. "
      - run: echo " This job is running on ${{ runner.os }} server hosted by github."
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}. "
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{github.repository}} has been cloned to the runner"
      - run: echo " The workflow is now ready to test your code in runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo " This Job's status is ${{ job.status }}. "
